export const PERU_FINANCIAL_SENDERS = [
  "bcp.com.pe",
  "interbank.com.pe",
  "notificacionesbcp.com.pe",
  "netinterbank.com.pe",
  "io.pe",
  "abaco.com.pe",
  "adyen.com",
  "adyen.com.pe",
  "aelucoop.com.pe",
  "afocat.com",
  "afocat.com.pe",
  "afphabitat.com.pe",
  "agora.pe",
  "agorapay.com",
  "agorapay.pe",
  "alfinbanco.pe",
  "americanexpress.com",
  "americanexpress.com.pe",
  "avancemos.com.pe",
  "avla.com",
  "avla.com.pe",
  "banbif.com.pe",
  "bancodecomercio.com.pe",
  "bancodelanacion.com.pe",
  "bancofalabella.pe",
  "bancognb.com.pe",
  "bancopichincha.com.pe",
  "bancoplaza.pe",
  "bancoripley.com.pe",
  "bbva.com.pe",
  "bbva.pe",
  "bcrp.gob.pe",
  "bim.com.pe",
  "bipay.pe",
  "bn.com.pe",
  "bvl.com",
  "bvl.com.pe",
  "cajaarequipa.com.pe",
  "cajaarequipa.pe",
  "cajadel-santa.com.pe",
  "cajahuancayo.com.pe",
  "cajalosandes.com.pe",
  "cajalosandes.pe",
  "cajamaynas.pe",
  "cajametropolitana.com.pe",
  "cajapaita.pe",
  "cajatrujillo.com.pe",
  "cardif.com",
  "cardif.com.pe",
  "cavali.com",
  "cavali.com.pe",
  "checkout.com",
  "checkout.com.pe",
  "chubb.com",
  "chubb.com.pe",
  "cmac-cusco.com.pe",
  "cmacica.com.pe",
  "cmacpiura.com.pe",
  "cmactacna.com.pe",
  "cofide.com.pe",
  "comparabien.com.pe",
  "compartamos.com.pe",
  "confianza.pe",
  "coopac.com.pe",
  "coopacnorandino.com.pe",
  "cooperativalosandes.com.pe",
  "cooperativaluzandina.com.pe",
  "cooperativasanpedro.com.pe",
  "credinka.com.pe",
  "crediscotia.com.pe",
  "crediurubamba.coop",
  "credscotia.com.pe",
  "culqi.com",
  "culqi.com.pe",
  "dinersclub.com",
  "dinersclub.com.pe",
  "dlocal.com",
  "dlocal.com.pe",
  "efectiva.com.pe",
  "financieraavancemos.com.pe",
  "financieraoh.com.pe",
  "fondomivivienda.com.pe",
  "fpay.pe",
  "global66.com",
  "global66.com.pe",
  "habitat.com.pe",
  "icbc.com.pe",
  "insur.com",
  "insur.com.pe",
  "integra.com.pe",
  "interseguro.com.pe",
  "interseguro.pe",
  "izipay.com",
  "izipay.com.pe",
  "izipayya.com",
  "kambista.com",
  "kambista.com.pe",
  "kontigo.pe",
  "lapositiva.com",
  "lapositiva.com.pe",
  "libertyseguros.com",
  "libertyseguros.com.pe",
  "ligo.com.pe",
  "ligo.pe",
  "losandes.org.pe",
  "lukita.pe",
  "luqea.pe",
  "mapfre.com",
  "mapfre.com.pe",
  "mastercard.com",
  "mastercard.com.pe",
  "maximo.pe",
  "mercadopago.com",
  "mercadopago.com.pe",
  "mibanco.com.pe",
  "mivivienda.com.pe",
  "moneygram.com",
  "moneygram.pe",
  "niubiz.com",
  "niubiz.com.pe",
  "oh.com.pe",
  "openpay.com",
  "openpay.pe",
  "pacifico.com.pe",
  "pacifico.coop",
  "pacificoseguros.com",
  "pagoefectivo.com.pe",
  "pagoefectivo.pe",
  "panda.pe",
  "payoneer.com",
  "payoneer.com.pe",
  "paypal.com",
  "paypal.com.pe",
  "payu.com",
  "payu.com.pe",
  "pichincha.pe",
  "plin.pe",
  "prestamype.com",
  "prestamype.com.pe",
  "prexcard.com",
  "prexpe.com",
  "prima.com.pe",
  "proempresa.com.pe",
  "profuturo.com.pe",
  "proinversion.gob.pe",
  "protecta.com.pe",
  "protectasecurity.com",
  "qapaq.com.pe",
  "qualitasperu.com",
  "qualitasperu.com.pe",
  "quillacoop.com.pe",
  "rappi.com.pe",
  "rappibank.com.pe",
  "rapyd.net",
  "rapyd.net.pe",
  "rebajatuscuentas.com",
  "rimac.com",
  "rimac.com.pe",
  "san-lorenzo.coop",
  "sanitas.com.pe",
  "santa-catalina.coop",
  "santa-maria-magdalena.coop",
  "santander.com.pe",
  "santo-cristode-bagua.coop",
  "sbs.gob.pe",
  "scotiabank.com.pe",
  "smv.gob.pe",
  "solven.com.pe",
  "solven.pe",
  "stripe.com",
  "stripe.com.pe",
  "tunki.com.pe",
  "tyba.com",
  "tyba.pe",
  "vendemas.com.pe",
  "viabcp.com",
  "visa.com",
  "visa.com.pe",
  "visanet.com.pe",
  "wayki.pe",
  "westernunion.com",
  "westernunion.com.pe",
  "wise.com",
  "yape.com",
  "yape.com.pe",
  "yellowpepper.com",
  "yellowpepper.com.pe",
];

export const SYNC_RANGES = ["30d", "3m", "6m", "12m"] as const;
export type SyncRange = (typeof SYNC_RANGES)[number];

export const DEFAULT_SYNC_RANGE: SyncRange = "3m";

const RANGE_DAYS: Record<SyncRange, number> = {
  "30d": 30,
  "3m": 90,
  "6m": 180,
  "12m": 365,
};

export function isSyncRange(value: unknown): value is SyncRange {
  return (
    typeof value === "string" &&
    (SYNC_RANGES as readonly string[]).includes(value)
  );
}

export function rangeToDays(range: SyncRange): number {
  return RANGE_DAYS[range];
}

export function formatGmailDate(date: Date): string {
  const year = date.getUTCFullYear();
  const month = String(date.getUTCMonth() + 1).padStart(2, "0");
  const day = String(date.getUTCDate()).padStart(2, "0");
  return `${year}/${month}/${day}`;
}

export function buildGmailQuery(since: Date): string {
  const senders = PERU_FINANCIAL_SENDERS.map(
    (sender) => `from:${sender}`,
  ).join(" OR ");
  return `(${senders}) after:${formatGmailDate(since)}`;
}